/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SystemAdminWorkspace;

import Hospital.City.CityDirectory;
import Hospital.Community.CommunityDirectory;
import Hospital.Hospital.HospitalDirectory;
import Hospital.House.HouseDirectory;
import Hospital.Patient.Patient;
import Hospital.Patient.PatientDirectory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author chinm
 */
public class SystemPatientPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientPanel
     */
    private PatientDirectory patientList;
    private CityDirectory cityList;
    private CommunityDirectory communityList;
    private HouseDirectory houseList;
    
    public SystemPatientPanel(PatientDirectory patientList,CityDirectory cityList,CommunityDirectory communityList,HouseDirectory houseList) {
        initComponents();
        this.patientList = patientList;
        this.cityList = cityList;
        this.communityList = communityList;
        this.houseList = houseList;
        populateTable();
        populateCity();
        populateState();
        populateCountry();
        populateComm();
        populateHouse();
        btnClear.setVisible(false);
        btnSave.setVisible(false);
//        btnClear.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtPhNo = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        scrollPanePatient = new javax.swing.JScrollPane();
        tablePatient = new javax.swing.JTable();
        lblPhNo = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        lblCommunity = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPatientId1 = new javax.swing.JLabel();
        txtPatientId = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblRole = new javax.swing.JLabel();
        txtRole = new javax.swing.JTextField();
        lblEmailId = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtGender = new javax.swing.JComboBox<>();
        lblState = new javax.swing.JLabel();
        txtState = new javax.swing.JComboBox<>();
        txtCommunity = new javax.swing.JComboBox<>();
        lblHouse = new javax.swing.JLabel();
        txtHouse = new javax.swing.JComboBox<>();
        txtCity = new javax.swing.JComboBox<>();
        lblCountry = new javax.swing.JLabel();
        txtCountry = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtPhNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhNoActionPerformed(evt);
            }
        });

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        lblName.setText("Name: ");

        lblAge.setText("Age: ");

        lblGender.setText("Gender: ");

        tablePatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Name", "Age", "Gender", "Phone No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollPanePatient.setViewportView(tablePatient);

        lblPhNo.setText("Phone No: ");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Patient Screen");

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAgeKeyPressed(evt);
            }
        });

        lblCity.setText("City:");

        lblCommunity.setText("Community:");

        lblUsername.setText("Username:");

        lblPatientId1.setText("Patient Id:");

        txtPatientId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPatientIdKeyPressed(evt);
            }
        });

        lblPassword.setText("Password:");

        lblRole.setText("Role:");

        txtRole.setEditable(false);
        txtRole.setText("Patient");

        lblEmailId.setText("Email Id:");

        txtEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIdActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Male", "Female", "Others" }));

        lblState.setText("State:");

        lblHouse.setText("House:");

        lblCountry.setText("Country:");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        lblSearch.setText("Search:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPhNo)
                                .addGap(39, 39, 39)
                                .addComponent(txtPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lblName)
                                            .addGap(60, 60, 60))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblRole)
                                                .addComponent(lblPatientId1)
                                                .addComponent(lblUsername))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtName)
                                        .addComponent(txtPatientId)
                                        .addComponent(txtUsername)
                                        .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblAge)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblGender)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEmailId)
                                .addGap(53, 53, 53)
                                .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSave))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCountry)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblState)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblCommunity)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                    .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCity)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblHouse)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPassword)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addComponent(scrollPanePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSearch)
                        .addGap(29, 29, 29)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete))
                    .addComponent(scrollPanePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHouse)
                            .addComponent(txtHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCommunity)
                            .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblState)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCity)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCountry)
                            .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRole)
                            .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPatientId1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsername))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAge))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGender))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmailId))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhNo)
                            .addComponent(btnClear)
                            .addComponent(btnSave))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPhNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhNoActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        btnClear.setVisible(false);
        btnSave.setVisible(false);
        String role = txtRole.getText();
        try {
            Integer pat = Integer.parseInt(txtPatientId.getText());
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this,"Please enter the Patient Id");
            return;
        }
        
        Integer patientId = Integer.parseInt(txtPatientId.getText());
        if(patientList.uiquePatientId(patientId) == false){
            JOptionPane.showMessageDialog(this, "Patient Id already exist");
            return;
        }
        String username = txtUsername.getText();
        if (username.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter Username");
            return;
        }
        else if(patientList.uniquePatientUsername(username) == false){
            JOptionPane.showMessageDialog(this, "Username already exist");
            return;
        }
        String name = txtName.getText();
        if (name.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter your Name");
            return;
        }
        
        try {
            Integer ag = Integer.parseInt(txtAge.getText());
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this,"Please enter the Age");
            return;
        }
        
        Integer age = Integer.parseInt(txtAge.getText());
        
        String gender = String.valueOf(txtGender.getSelectedItem());
        if (txtGender.getSelectedItem().equals("--Select--")){
            JOptionPane.showMessageDialog(this, "Please select your Gender");
            return;
        }
        
        try {
            Long ph = Long.parseLong(txtPhNo.getText());
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this,"Please enter the phone No.");
            return;
        }
        
        Long phno = Long.parseLong(txtPhNo.getText());
        String phNo = String.valueOf(phno);
        
        if (phNo.length()!= 10){
            JOptionPane.showMessageDialog(this, "Please enter a valid Phone number");
            return;
        }
        String email = txtEmailId.getText();
        if (email.matches("(.*)@(.*).com")){
            
        }
        else{
            JOptionPane.showMessageDialog(this, "Please enter a valid Email Id");
            return;
        }
        String house = String.valueOf(txtHouse.getSelectedItem());
        if (txtHouse.getSelectedItem().equals("--Select--")){
            JOptionPane.showMessageDialog(this, "Please select the House.");
            return;
        }
        String city = String.valueOf(txtCity.getSelectedItem());
        if (txtCity.getSelectedItem().equals("--Select--")){
            JOptionPane.showMessageDialog(this, "Please select the City.");
            return;
        }
        String community = String.valueOf(txtCommunity.getSelectedItem());
        if (txtCommunity.getSelectedItem().equals("--Select--")){
            JOptionPane.showMessageDialog(this, "Please select the Community.");
            return;
        }
        String state = String.valueOf(txtState.getSelectedItem());
        if (txtState.getSelectedItem().equals("--Select--")){
            JOptionPane.showMessageDialog(this, "Please select the State.");
            return;
        }
        String country = String.valueOf(txtCountry.getSelectedItem());
        if (txtCountry.getSelectedItem().equals("--Select--")){
            JOptionPane.showMessageDialog(this, "Please select the Country.");
            return;
        }
//        String address = txtAddress.getText();
        char[] pass = txtPassword.getPassword();
        String password = new String(pass);
        if (txtPassword.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter your Password.");
            return;
        }
        Patient newPatient = patientList.addPatient();
        
        newPatient.setRole(role);
        newPatient.setPatientId(patientId);
        newPatient.setUsername(username);
        newPatient.setName(name);
        newPatient.setAge(age);
        newPatient.setGender(gender);
        newPatient.setPhno(phno);
        newPatient.setEmail(email);
        newPatient.setState(state);
        newPatient.setCity(city);
        newPatient.setCommunity(community);
        newPatient.setHouse(house);
        newPatient.setCountry(country);
//        newPatient.setAddress(address);
        newPatient.setPassword(password);
        
        JOptionPane.showMessageDialog(this, "Patient Created Successfully");
        
        txtPatientId.setText("");
        txtUsername.setText("");
        txtName.setText("");
        txtAge.setText("");
        txtGender.setSelectedIndex(0);
        txtPhNo.setText("");
        txtEmailId.setText("");
        txtHouse.setSelectedIndex(0);
        txtCountry.setSelectedIndex(0);
        txtState.setSelectedIndex(0);
        txtCity.setSelectedIndex(0);
        txtCommunity.setSelectedIndex(0);
//        txtAddress.setText("");
        txtPassword.setText("");
        
        populateTable();
        
    }//GEN-LAST:event_btnCreateActionPerformed

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tablePatient.getModel();
        model.setRowCount(0);
        
        for(Patient pat : patientList.getPatientList()){
            
            Object[] row = new Object[5];
            row[0] = pat; 
            row[1] = pat.getName();
            row[2] = pat.getAge();
            row[3] = pat.getGender();
            row[4] = pat.getPhno();
             
            model.addRow(row);
        }
    }
    
    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        btnSave.setVisible(false);
        btnClear.setVisible(true);
        Integer selectedRowIndex = tablePatient.getSelectedRow();
        
        if (selectedRowIndex<0){
            
            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }
        
        else{
            DefaultTableModel model = (DefaultTableModel) tablePatient.getModel();
            Patient selectedPat = (Patient) model.getValueAt(selectedRowIndex,0);

            txtPatientId.setText(String.valueOf(selectedPat.getPatientId()));
            txtUsername.setText(selectedPat.getUsername());
            txtName.setText(selectedPat.getName());
            txtAge.setText(String.valueOf(selectedPat.getAge()));
            txtGender.setSelectedItem(selectedPat.getGender());
            txtPhNo.setText(String.valueOf(selectedPat.getPhno()));
            txtEmailId.setText(selectedPat.getEmail());
            txtCountry.setSelectedItem(selectedPat.getCountry());
            txtState.setSelectedItem(selectedPat.getState());
            txtCity.setSelectedItem(selectedPat.getCity());
            txtCommunity.setSelectedItem(selectedPat.getCommunity());
            txtHouse.setSelectedItem(selectedPat.getHouse());
//            txtAddress.setText(selectedPat.getAddress());
            txtPassword.setText(selectedPat.getPassword());
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIdActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        btnClear.setVisible(false);
        btnSave.setVisible(false);
        Integer selectedRowIndex = tablePatient.getSelectedRow();
        
        if (selectedRowIndex<0){
            
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }
        
        else{
            DefaultTableModel model = (DefaultTableModel) tablePatient.getModel();
            Patient selectedPat = (Patient) model.getValueAt(selectedRowIndex,0);
            
            patientList.deletePatient(selectedPat);
            
            JOptionPane.showMessageDialog(this, "Patient deleted successfully.");
            populateTable();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtPatientId.setText("");
        txtUsername.setText("");
        txtName.setText("");
        txtAge.setText("");
        txtGender.setSelectedIndex(0);
        txtPhNo.setText("");
        txtEmailId.setText("");
        txtHouse.setSelectedIndex(0);
        txtCountry.setSelectedIndex(0);
        txtState.setSelectedIndex(0);
        txtCity.setSelectedIndex(0);
        txtCommunity.setSelectedIndex(0);
//        txtAddress.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        btnSave.setVisible(true);
        btnClear.setVisible(true);
        Integer selectedRowIndex = tablePatient.getSelectedRow();
        
        if (selectedRowIndex<0){
            
            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }
        
        else{
            DefaultTableModel model = (DefaultTableModel) tablePatient.getModel();
            Patient selectedPat = (Patient) model.getValueAt(selectedRowIndex,0);

            txtPatientId.setText(String.valueOf(selectedPat.getPatientId()));
            txtUsername.setText(selectedPat.getUsername());
            txtName.setText(selectedPat.getName());
            txtAge.setText(String.valueOf(selectedPat.getAge()));
            txtGender.setSelectedItem(selectedPat.getGender());
            txtPhNo.setText(String.valueOf(selectedPat.getPhno()));
            txtEmailId.setText(selectedPat.getEmail());
            txtCountry.setSelectedItem(selectedPat.getCountry());
            txtState.setSelectedItem(selectedPat.getState());
            txtCity.setSelectedItem(selectedPat.getCity());
            txtCommunity.setSelectedItem(selectedPat.getCommunity());
            txtHouse.setSelectedItem(selectedPat.getHouse());
//            txtAddress.setText(selectedPat.getAddress());
            txtPassword.setText(selectedPat.getPassword());
            
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Integer selectedRowIndex = tablePatient.getSelectedRow();
        
        if (selectedRowIndex<0){
            
            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }
        
        else{
            DefaultTableModel model = (DefaultTableModel) tablePatient.getModel();
            Patient selectedPat = (Patient) model.getValueAt(selectedRowIndex,0);
            
            selectedPat.setPatientId(Integer.parseInt(txtPatientId.getText()));
           
            if(patientList.uiquePatientId(Integer.parseInt(txtPatientId.getText())) == false){
                JOptionPane.showMessageDialog(this, "Patient Id already exist");
                return;
            }
            selectedPat.setUsername(txtUsername.getText());
            if (txtUsername.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter Username");
            return;
            }
            else if(patientList.uniquePatientUsername(txtUsername.getText()) == false){
                JOptionPane.showMessageDialog(this, "Username already exist");
                return;
            }
            
            selectedPat.setName(txtName.getText());
            if (txtName.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Please enter your Name");
                return;
            }
            
            selectedPat.setAge(Integer.parseInt(txtAge.getText()));
            
            
            selectedPat.setGender(String.valueOf(txtGender.getSelectedItem()));
            if (txtGender.getSelectedItem().equals("--Select--")){
                JOptionPane.showMessageDialog(this, "Please select your Gender");
                return;
            }
            selectedPat.setPhno(Long.parseLong(txtPhNo.getText()));
            
            selectedPat.setEmail(txtEmailId.getText());
           
            selectedPat.setCity(String.valueOf(txtCity.getSelectedItem()));
            if (txtCity.getSelectedItem().equals("--Select--")){
                JOptionPane.showMessageDialog(this, "Please select the City.");
                return;
            }
            selectedPat.setCommunity(String.valueOf(txtCommunity.getSelectedItem()));
            if (txtCommunity.getSelectedItem().equals("--Select--")){
                JOptionPane.showMessageDialog(this, "Please select the Community.");
                return;
            }
            selectedPat.setHouse(String.valueOf(txtHouse.getSelectedItem()));
            if (txtHouse.getSelectedItem().equals("--Select--")){
                JOptionPane.showMessageDialog(this, "Please select the House.");
                return;
            }
            selectedPat.setState(String.valueOf(txtState.getSelectedItem()));
            if (txtState.getSelectedItem().equals("--Select--")){
                JOptionPane.showMessageDialog(this, "Please select the State.");
                return;
            }
            selectedPat.setCountry(String.valueOf(txtCountry.getSelectedItem()));
            if (txtCountry.getSelectedItem().equals("--Select--")){
                JOptionPane.showMessageDialog(this, "Please select the Country.");
                return;
            }
//            selectedPat.setAddress(txtAddress.getText());
            selectedPat.setPassword(txtPassword.getText());
            if (txtPassword.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter your Password.");
                return;
            }
            JOptionPane.showMessageDialog(this, "Patient details updated successfully.");
            
            populateTable();
            
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String searchQuery = txtSearch.getText();
        Search(searchQuery);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtPatientIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPatientIdKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            txtPatientId.setEditable(false);
        }
        else{
            txtPatientId.setEditable(true);
        }
    }//GEN-LAST:event_txtPatientIdKeyPressed

    private void txtAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            txtAge.setEditable(false);
        }
        else{
            txtAge.setEditable(true);
        }
    }//GEN-LAST:event_txtAgeKeyPressed
    
    public void populateHouse(){
        String[] houArr = houseList.houseArray();
        DefaultComboBoxModel h = new DefaultComboBoxModel(houArr);
        txtHouse.setModel(h);
    }
    
    public void populateCity(){
        String[] cityArr = cityList.cityArray();
        DefaultComboBoxModel c = new DefaultComboBoxModel(cityArr);
        txtCity.setModel(c);
    }
    
    public void populateState(){
        String[] stateArr = cityList.stateArray();
        DefaultComboBoxModel s = new DefaultComboBoxModel(stateArr);
        txtState.setModel(s);
    }
    
    public void populateCountry(){
        String[] countryArr = cityList.countryArray();
        DefaultComboBoxModel c = new DefaultComboBoxModel(countryArr);
        txtCountry.setModel(c);
    }
    
     public void populateComm(){
        String[] commArr = communityList.commArray();
        DefaultComboBoxModel c = new DefaultComboBoxModel(commArr);
        txtCommunity.setModel(c);
    }


    private void Search(String searchQuery){
        DefaultTableModel model = (DefaultTableModel) tablePatient.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        
        tablePatient.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(searchQuery));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblEmailId;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHouse;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPatientId1;
    private javax.swing.JLabel lblPhNo;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JScrollPane scrollPanePatient;
    private javax.swing.JTable tablePatient;
    private javax.swing.JTextField txtAge;
    private javax.swing.JComboBox<String> txtCity;
    private javax.swing.JComboBox<String> txtCommunity;
    private javax.swing.JComboBox<String> txtCountry;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JComboBox<String> txtGender;
    private javax.swing.JComboBox<String> txtHouse;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPatientId;
    private javax.swing.JTextField txtPhNo;
    private javax.swing.JTextField txtRole;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JComboBox<String> txtState;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
